version: '2'
services:
  mongo:
    image: mongo:4.2.6
    container_name: "mongodb"
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=poker
      - MONGO_INITDB_ROOT_PASSWORD=poker

